import { makeStyles } from '@material-ui/core/styles';

export const CSSGoalsRightPanel = makeStyles({
    root:{
        width:window.innerWidth-500,
        minWidth:600,
        height:window.innerHeight-300
    },
    main:{
        padding:10
    },
    header:{
        width:'50%'
    },
    footer:{
    },
    label:{
        height:30,
        paddingTop:10,
        display:'inline-block'
    },
    input:{
        height:30,
        display:'inline-block'
    },
    divider:{
        marginTop:20,
        marginBottom:20
    },
    feedbackDisabled:{
        height:100,
        display:'inline-block',
        resize:'none'
    },
    inputDisabled:{
        textAlign:"right",
        display:'inline-block',
        marginTop:10
    },
    feedback:{
        height:230,
        display:'inline-block'
    },
    list:{
        height:window.innerHeight-400
    },
    listOther:{
        marginTop:20,
        height:window.innerHeight-420
    },
    topRow:{
        paddingBottom:10,
        height:45
    },
    iconBtn:{
        width:30, 
        height:20,
        cursor:'pointer'
    },
    iconBtnHolder:{
        position:'absolute', 
        paddingRight:10, 
        paddingLeft:10, 
        paddingTop:8
    }
})