export const SHOW_PAGE = 'SHOW_PAGE';
export const ZONE_SELECTED = 'ZONE_SELECTED';
export const QUARTER_SELECTED = 'QUARTER_SELECTED';
export const YEAR_SELECTED = 'YEAR_SELECTED';
export const SHOW_LOADER = 'SHOW_LOADER';
export const SHOW_MODEL = 'SHOW_MODEL';
export const MEMBER_ASSIGNED = 'MEMBER_ASSIGNED';
export const ROTATION_SHEET_CREATED = 'ROTATION_SHEET_CREATED';
export const DATABASE_BACKUP_SUCCESS = 'DATABASE_BACKUP_SUCCESS';
export const TEAM_LIST = 'TEAM_LIST';
export const UPDATE_QUARTER_LIST = 'UPDATE_QUARTER_LIST';
export const CHANGE_GOAL_PERCENT = 'CHANGE_GOAL_PERCENT';
export const PREVIEW_GOAL = 'PREVIEW_GOAL';
export const UDPATE_ZONE_LIST = 'UDPATE_ZONE_LIST';

export const REGISTER_SUCCESS = 'REGISTER_USER';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const FORGET_PASS_SUCCESS = 'FORGET_PASS_SUCCESS';
export const FORGET_PASS_FAIL = 'FORGET_PASS_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SERVER_ERRORS = 'INTERNAL_ERRORS';

export const DESIGNER_ADDED = 'DESIGNER_ADDED';
export const ASSIGN_DESIGNER = 'ASSIGN_DESIGNER';
export const DESIGNER_REMOVED = 'DESIGNER_REMOVED';
export const DESIGNER_SELECTED = 'DESIGNER_SELECTED';
export const DESIGNERS_COLLECTED = 'DESIGNERS_COLLECTED';
export const DESIGNERS_DATA_COLLECTED = 'DESIGNERS_DATA_COLLECTED';
export const SAVE_DESIGNER_VALUE = 'SAVE_DESIGNER_VALUE';
export const DESIGNER_VALUE_SAVED = 'DESIGNER_VALUE_SAVED';
export const DESIGNER_TO_REMOVE = 'DESIGNER_TO_REMOVE';
export const DESIGNER_DATA_PUBLISHED = 'DESIGNER_DATA_PUBLISHED';

export const AM_SELECTED = 'AM_SELECTED';
export const AST_MANAGERS_COLLECTED = 'AST_MANAGER_COLLECTED';

export const SAVE_FEEDBACK = 'SAVE_FEEDBACK';
export const RESET_FEEDBACK = 'RESET_FEEDBACK';
export const CHANGE_FEEDBACK = 'CHANGE_FEEDBACK';

export const SAVE_OTHER_FEEDBACK = 'SAVE_OTHER_FEEDBACK';
export const RESET_OTHER_FEEDBACK = 'RESET_OTHER_FEEDBACK';
export const CHANGE_OTHER_FEEDBACK = 'CHANGE_OTHER_FEEDBACK';
